# The docker-compose.yml file describes the services that make your app. In this example those services are a web server and database. 
# The compose file also describes which Docker images these services use, how they link together, any volumes they might need to be mounted inside the containers. 
# Finally, the docker-compose.yml file describes which ports these services expose. See the docker-compose.yml reference for more information on how this file works.

version: "3.9"
   
services:
  db1:
    image: postgres
    container_name: db1
    environment:
      - POSTGRES_DB=cloud_db
      - POSTGRES_USER=cloud_admin
      - POSTGRES_PASSWORD=password
  db2:
    image: postgres
    container_name: db2
    environment:
      - POSTGRES_DB=cloud_db
      - POSTGRES_USER=cloud_admin
      - POSTGRES_PASSWORD=password


  web1:
    #build: ./restApi/restApi
    build: .
    container_name: web1
    volumes:
      - .:/code
    ports:
      - "8001:8000"    
    env_file:
    - restApi/db1.env
    #- restApi/restApi/restApi/.env    
    depends_on:
      - db1
  web2:
    build: .
    container_name: web2
    volumes:
      - .:/code
    ports:
      - "8002:8000"    
    env_file:
    - restApi/db2.env   
    depends_on:
      - db2


  nginx1:
    container_name: nginx1
    build: ./nginx
    ports:
      - "81:80"
    links:
      - web1
  nginx2:
    container_name: nginx2
    build: ./nginx/load_balancer
    ports:
      - "82:80"
    links:
      - web1
      - web2