# The docker-compose.yml file describes the services that make your app. In this example those services are a web server and database. 
# The compose file also describes which Docker images these services use, how they link together, any volumes they might need to be mounted inside the containers. 
# Finally, the docker-compose.yml file describes which ports these services expose. See the docker-compose.yml reference for more information on how this file works.

version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=cloud_db
      - POSTGRES_USER=cloud_admin
      - POSTGRES_PASSWORD=password
  web:
    build: ./restApi/restApi
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    container_name: web
    env_file:
    - restApi/restApi/restApi/.env
    depends_on:
      - db
  # nginx:
  #   build: ./nginx
  #   ports:
  #     - "80:80"